//! Build script: produce a small `fixture.mem` archive in `OUT_DIR`
//! for the wasm-bindgen smoke tests to embed via `include_bytes!`.
//!
//! The fixture has two entities, `alpha.md` and `beta.md`, pinned
//! against the default schema. The archive is generated by the same
//! `Engine::export_mem_to_bytes` path browsers consume in
//! production, so the test exercises the real hydrate code rather
//! than a hand-rolled zip.
//!
//! Run only when `OUT_DIR` is set (i.e., during a `cargo build` —
//! `rustc --check-cfg` etc. set it). The script writes a single
//! artifact and reruns only when its source changes.

use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    // We only need the fixture when building tests / examples that
    // consume it. Skip if `OUT_DIR` is unset (shouldn't happen with
    // Cargo, but keeps the script defensive).
    let out_dir = match std::env::var_os("OUT_DIR") {
        Some(dir) => PathBuf::from(dir),
        None => return,
    };

    let bytes = build_fixture_bytes();
    let out_path = out_dir.join("fixture.mem");
    std::fs::write(&out_path, bytes).expect("write fixture.mem");
}

fn build_fixture_bytes() -> Vec<u8> {
    use memstead_base::backend::MemBackend;
    use memstead_base::engine::Engine;
    use memstead_base::storage::FilesystemMemWriter;
    use memstead_base::vcs::{Actor, ClientId};
    use memstead_base::workspace::{Mount, MountCapability, MountLifecycle, MountStorage};
    use memstead_schema::SchemaRef;

    let tmp = tempfile::TempDir::new().expect("tempdir");
    let mem_dir = tmp.path().join("specs");
    std::fs::create_dir_all(mem_dir.join(".memstead")).expect("mkdir .memstead");
    std::fs::write(
        mem_dir.join(".memstead").join("config.json"),
        br#"{ "format": 1, "schema": "default@1.0.0", "version": "1.0.0" }"#,
    )
    .expect("write config.json");

    let mount = Mount {
        mem: "specs".to_string(),
        schema: Some(SchemaRef::new("default", semver::Version::new(1, 0, 0))),
        storage: MountStorage::Folder {
            path: mem_dir.clone(),
        },
        capability: MountCapability::Write,
        lifecycle: MountLifecycle::Eager,
        cross_linkable: true,
        migration_target: None,
    };
    let writer = FilesystemMemWriter::new(mem_dir.clone());
    let mut engine = Engine::from_mounts(vec![(mount, Box::new(writer) as Box<dyn MemBackend>)])
        .expect("from_mounts");

    let actor = Actor::Cli;
    let client = ClientId {
        name: "build-script".to_string(),
        version: "0.0.0".to_string(),
    };
    for title in ["Alpha", "Beta"] {
        let mut sections = indexmap::IndexMap::new();
        sections.insert(
            "identity".to_string(),
            format!("{title} is a fixture spec."),
        );
        sections.insert(
            "purpose".to_string(),
            "Exercises the wasm-bindgen hydrate path.".to_string(),
        );
        let args = memstead_base::engine::CreateEntityArgs {
            anchors: Vec::new(),
            mem: "specs".to_string(),
            title: title.to_string(),
            entity_type: "spec".to_string(),
            sections,
            metadata: indexmap::IndexMap::new(),
            relations: Vec::new(),
            dry_run: false,
        };
        engine
            .create_entity(args, actor, Some(&client), None)
            .expect("create_entity");
    }
    engine
        .export_mem_to_bytes("specs")
        .expect("export_mem_to_bytes")
}
