//! Smoke tests for the `@memstead/wasm` JS bindings, run in Node
//! (decision 10, backlog-sweep plan 04): the assertions cover the
//! published API surface (hydration, `getEntity`, `entityIds`, commit
//! application, typed refusals) and none of them needs a browser API —
//! a nodejs-target run executes them on every CI push with no
//! chromedriver. Run with:
//!
//! ```ignore
//! wasm-pack test --node crates/memstead-wasm
//! ```
//!
//! Three smoke tests:
//!
//! - `from_snapshot_then_get_entity` — hydrate a `.mem` archive in
//!   wasm, look one entity up.
//! - `apply_commit_then_get_entity_after` — apply a `Modified`
//!   envelope, confirm the new body is visible.
//! - `search_refuses_with_typed_code` — calling `engine.search(...)`
//!   throws the `SEARCH_UNAVAILABLE_IN_WASM` envelope.
//!
//! `fixture.mem` is generated at build time by the crate's
//! [`build.rs`](../build.rs): a tiny two-entity folder mem
//! (`alpha`, `beta`) round-tripped through
//! `Engine::export_mem_to_bytes`. Embedding the bytes via
//! `include_bytes!` keeps the test self-contained — no fetch, no
//! filesystem.

#![cfg(target_arch = "wasm32")]

use memstead_wasm::Engine;
use wasm_bindgen::JsCast;
use wasm_bindgen::JsValue;
use wasm_bindgen_test::*;

const FIXTURE_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/fixture.mem"));

fn hydrate() -> Engine {
    Engine::from_snapshot(FIXTURE_BYTES.to_vec())
        .expect("fromSnapshot must succeed on the build-script fixture")
}

#[wasm_bindgen_test]
fn from_snapshot_then_get_entity() {
    let engine = hydrate();
    let v = engine
        .get_entity("specs--alpha")
        .expect("getEntity must not throw on a present id");
    assert!(
        !v.is_undefined(),
        "specs--alpha must be present after fromSnapshot"
    );
}

/// The self-sufficiency test: a page handed ONLY the archive and the
/// published package can find out what is inside it and read one back.
///
/// This is what the package's stated purpose requires and what it could
/// not do — `getEntity` needs an id and nothing produced one, so every
/// caller had to pair the snapshot with an id list generated by the
/// CLI. The test deliberately uses no fixture knowledge beyond the
/// bytes: ids come from `entityIds()`, and the entity read back is
/// whichever one that returned first.
#[wasm_bindgen_test]
fn entity_ids_makes_a_snapshot_self_sufficient() {
    let engine = hydrate();

    let ids_js = engine
        .entity_ids(None)
        .expect("entityIds must not throw on a hydrated snapshot");
    let ids: Vec<String> =
        serde_wasm_bindgen::from_value(ids_js).expect("entityIds returns strings");
    assert!(
        ids.len() >= 2,
        "the fixture carries two entities; got {ids:?}"
    );
    // Sorted, so a page rendering the list is stable across reloads.
    let mut sorted = ids.clone();
    sorted.sort();
    assert_eq!(ids, sorted, "entityIds must return sorted ids");

    // Every id it named must be readable — the round trip that makes
    // the archive self-contained.
    for id in &ids {
        let v = engine
            .get_entity(id)
            .unwrap_or_else(|_| panic!("getEntity threw for id {id} that entityIds named"));
        assert!(
            !v.is_undefined(),
            "entityIds named {id}, but getEntity does not have it"
        );
    }

    // `mem` narrows; an unknown mem is an empty answer, not a throw.
    let mem = engine
        .mem_names()
        .ok()
        .and_then(|v| serde_wasm_bindgen::from_value::<Vec<String>>(v).ok())
        .and_then(|m| m.into_iter().next())
        .expect("fixture has at least one mem");
    let scoped: Vec<String> =
        serde_wasm_bindgen::from_value(engine.entity_ids(Some(mem.clone())).unwrap()).unwrap();
    assert_eq!(scoped, ids, "the fixture's single mem holds every id");
    let none: Vec<String> =
        serde_wasm_bindgen::from_value(engine.entity_ids(Some("no-such-mem".into())).unwrap())
            .expect("an unknown mem returns an empty array rather than throwing");
    assert!(none.is_empty(), "got {none:?}");
}

#[wasm_bindgen_test]
fn apply_commit_then_get_entity_after() {
    let mut engine = hydrate();

    // Hand-build a minimal CommitEnvelope JS object — same JSON shape
    // the bridge's `/commits` endpoint produces.
    let envelope_js = js_sys::eval(
        r#"({
            sha: "new-sha",
            parent: "",
            mem: "specs",
            timestamp: "2026-05-19T10:00:00Z",
            trailers: {},
            changes: [{
                op: "modified",
                path: "alpha.md",
                content: "---\ntype: spec\ncreated_date: 2026-01-01\nlast_modified: 2026-01-01\n---\n# Alpha Renamed\n\n## Identity\n\nAlpha Renamed body\n"
            }]
        })"#,
    )
    .expect("eval envelope literal");

    engine
        .apply_commit(envelope_js)
        .expect("applyCommit must accept a well-formed envelope");

    let v = engine
        .get_entity("specs--alpha")
        .expect("getEntity must not throw");
    assert!(
        !v.is_undefined(),
        "specs--alpha must still exist after Modified apply"
    );
    // Title is the first `#`-heading — confirm it reflects the new
    // body by serialising back through JSON and parsing.
    let json = js_sys::JSON::stringify(&v).expect("stringify entity");
    let s: String = json.dyn_into::<js_sys::JsString>().unwrap().into();
    assert!(
        s.contains("Alpha Renamed"),
        "modified body must surface in the stored title; got {s}"
    );
}

/// The cold-start F11 reproducer: `Engine.fromSnapshot(bytes).health()`
/// trapped (`RuntimeError: unreachable` out of `SystemTime::now`) and
/// poisoned the instance. Pin the trap-free property: health() returns
/// the `memstead_health`-shaped summary — staleness fields included,
/// since the staleness computation is exactly what read the clock — and
/// the instance stays usable afterwards.
#[wasm_bindgen_test]
fn health_returns_summary_without_trapping_and_instance_survives() {
    let engine = hydrate();

    let summary = engine
        .health()
        .expect("health() must not throw on wasm32 (F11: it used to trap)");
    let json = js_sys::JSON::stringify(&summary).expect("stringify health summary");
    let s: String = json.dyn_into::<js_sys::JsString>().unwrap().into();
    for field in ["stale_entities", "orphan_count", "stub_count"] {
        assert!(
            s.contains(field),
            "health summary must carry the memstead_health shape (missing {field}): {s}"
        );
    }

    // The trap poisoned the instance for every later call — prove this
    // one survives: health() again, then a read.
    engine
        .health()
        .expect("second health() call must succeed (instance not poisoned)");
    let v = engine
        .get_entity("specs--alpha")
        .expect("getEntity must still work after health()");
    assert!(!v.is_undefined(), "reads must survive health()");
}

#[wasm_bindgen_test]
fn search_refuses_with_typed_code() {
    let engine = hydrate();
    let err = engine
        .search(JsValue::NULL)
        .expect_err("search must refuse on wasm32");

    let code_js = js_sys::Reflect::get(&err, &JsValue::from_str("code")).unwrap_or(JsValue::NULL);
    let code: String = code_js
        .as_string()
        .expect("search refuse envelope must carry a string `code`");
    assert_eq!(
        code, "SEARCH_UNAVAILABLE_IN_WASM",
        "expected SEARCH_UNAVAILABLE_IN_WASM, got {code}"
    );
}
