// Vault-DB-shaped fixture builder for engine integration tests.
//
// Replaces the previous on-disk fixture under
// `tests/fixtures/workspace-rewrite/`: instead of committing a static
// disk tree (which now lacks the `vault-repo/.git/` half of the
// cutover-shape), this builder writes a fresh workspace at test setup
// time with both halves present.
//
// Disk-side: `.memstead/workspace.toml`, per-vault `.memstead/config.json`, and
// workspace-level `schemas/software` + `schemas/planning` trees. Used
// by `Engine::init_with_settings` for config + schema resolution and
// by `entity::loader::load_vault` for entity reads.
//
// Vault-DB-side: a bare `vault-repo/.git/` repository with `main`
// (operator-facing docs only), `__MEMSTEAD` (unified schemas +
// per-vault configs), and five orphan branches — `engine`, `macos`,
// `plugin`, `web`, `example-plan` — each with one empty initial
// commit per design decision D7.
//
// Every vault's `vcs.gitdir` points at the shared `vault-repo/.git/` and
// `vcs.worktree` at the workspace root, so engine init under
// `StorageAdapterChoice::GitObject` wires each vault's writer to its
// own `refs/heads/<vault>` against the same gitdir — exactly the
// cutover-shape that production uses.
//
// This file is included via `include!()` from a consuming crate's test
// file (today: `memstead-git-branch/tests/workspace_rewrite_fixture.rs`) so the
// consuming crate supplies the `gix` dependency (memstead-schema does not
// depend on `gix`). The schema seed YAMLs under
// `tests/fixtures/seed/schemas/` are read at test-setup time via
// `CARGO_MANIFEST_DIR`-relative paths so the builder works from any
// working directory.

use std::fs;
use std::path::{Path, PathBuf};

/// Handle returned by [`build_fixture`] — both halves of the staged
/// workspace, useful for tests that want to assert against either the
/// disk tree (config + schemas) or the vault-repo gitdir directly.
#[allow(dead_code)] // fields read by some consuming tests, not all
pub(crate) struct VaultRepoHandle {
    /// Workspace root containing `.memstead/workspace.toml`, vault dirs, schemas/,
    /// and `vault-repo/`. Pass this to `Engine::init_with_settings` as
    /// `WorkspaceSettings.workspace_root`.
    pub workspace_root: PathBuf,
    /// Bare gitdir at `<workspace_root>/vault-repo/.git/`. Each vault's
    /// `vcs.gitdir` resolves to this path; `GitTreeVaultWriter` targets
    /// `refs/heads/<vault>` here.
    pub vault_repo_gitdir: PathBuf,
}

/// The vault roster materialised on every fixture. Tuple of
/// `(vault-relative-path, vault-name, schema-name, belongs_to)`. Order
/// is the `.memstead/workspace.toml` declaration order — preserved verbatim by the
/// builder so tests asserting on iteration order have a stable shape.
const VAULTS: &[(&str, &str, &str, &[&str])] = &[
    ("project_vaults/engine", "engine", "software@0.1.0", &[]),
    ("project_vaults/macos", "macos", "software@0.1.0", &[]),
    ("project_vaults/plugin", "plugin", "software@0.1.0", &[]),
    ("project_vaults/web", "web", "software@0.1.0", &[]),
    (
        "exec_vaults/example-plan",
        "example-plan",
        "planning@0.1.0",
        &["engine", "macos", "plugin", "web"],
    ),
];

/// README placeholder committed at `main:README.md` — distinct content
/// is irrelevant for engine tests; only the path's presence matters.
const README_BODY: &str =
    "# vault-repo fixture\n\nProgrammatically generated by `vault_repo_seed::build_fixture`.\n";

/// Stage a fresh vault-repo-shaped workspace under `temp_dir`. Returns a
/// [`VaultRepoHandle`] pointing at the workspace root and gitdir.
///
/// `temp_dir` must already exist; the builder writes files and
/// directories underneath it but does not own its lifetime — callers
/// pass a `tempfile::TempDir`'s `path()` and keep the guard alive.
#[allow(dead_code)] // entry point for include!()-ing tests
pub(crate) fn build_fixture(temp_dir: &Path) -> VaultRepoHandle {
    let workspace_root = temp_dir.to_path_buf();

    // ---- Disk-side: .memstead/workspace.toml ----
    let memstead_dir = workspace_root.join(".memstead");
    fs::create_dir_all(&memstead_dir).expect("create workspace .memstead dir");
    fs::write(memstead_dir.join("workspace.toml"), memstead_toml())
        .expect("write workspace .memstead/workspace.toml");

    // ---- Disk-side: schemas/ (copied from committed seed) ----
    let seed_schemas = seed_schemas_root();
    let dst_schemas = workspace_root.join("schemas");
    copy_tree(&seed_schemas, &dst_schemas);

    // ---- Disk-side: per-vault dirs with .memstead/config.json ----
    for (rel, name, schema, belongs_to) in VAULTS {
        let vault_dir = workspace_root.join(rel);
        fs::create_dir_all(vault_dir.join(".memstead")).expect("create vault .memstead dir");
        fs::write(
            vault_dir.join(".memstead").join("config.json"),
            vault_config_json(name, schema, belongs_to),
        )
        .expect("write vault config.json");
    }

    // ---- Vault-DB-side: vault-repo/.git/ with main + per-vault branches ----
    let vault_repo_root = workspace_root.join("vault-repo");
    let vault_repo_gitdir = vault_repo_root.join(".git");
    fs::create_dir_all(&vault_repo_root).expect("create vault-repo dir");
    gix::init_bare(&vault_repo_gitdir).expect("init vault-repo gitdir");

    let repo = gix::open(&vault_repo_gitdir).expect("open vault-repo gitdir");

    // main: README only. Configs + schemas live under the unified
    // `__MEMSTEAD` ref (sealed below).
    let mut editor = repo.empty_tree().edit().expect("init main tree editor");

    let readme_blob = repo
        .write_blob(README_BODY.as_bytes())
        .expect("write README blob")
        .detach();
    editor
        .upsert(
            "README.md",
            gix::object::tree::EntryKind::Blob,
            readme_blob,
        )
        .expect("upsert README");

    let main_tree = editor.write().expect("write main tree").detach();
    let actor = fixture_signature();
    let mut buf = gix::date::parse::TimeBuf::default();
    let actor_ref = actor.to_ref(&mut buf);
    repo.commit_as(
        actor_ref,
        actor_ref,
        "refs/heads/main",
        "vault-repo-seed: programmatic fixture",
        main_tree,
        Vec::<gix::ObjectId>::new(),
    )
    .expect("commit main");

    // ---- __MEMSTEAD: schemas + per-vault configs in one unified tree.
    // Inline rather than calling
    // `memstead_git_branch::storage_memstead::migrate_to_memstead_ref` because
    // `memstead-schema` does not depend on `memstead-git-branch` (the include!()
    // consuming crate supplies gix). The projection mirrors what the
    // production migrator produces — `schemas/<name>@<version>/...` for
    // each schema and `vaults/<name>/config.json` for each per-vault
    // entry.
    let mut memstead_editor = repo.empty_tree().edit().expect("init __MEMSTEAD tree editor");
    // Schemas: walk the disk schemas dir for `<name>/schema.yaml` and
    // copy each subtree into `schemas/<name>@<version>/`.
    if let Ok(rd) = fs::read_dir(&dst_schemas) {
        for entry in rd.flatten() {
            let path = entry.path();
            if !path.is_dir() {
                continue;
            }
            let name = match path.file_name().and_then(|s| s.to_str()) {
                Some(n) => n.to_string(),
                None => continue,
            };
            let manifest_path = path.join("schema.yaml");
            let manifest = match fs::read_to_string(&manifest_path) {
                Ok(s) => s,
                Err(_) => continue,
            };
            // Hand-roll YAML scan for `version: <X.Y.Z>` (matches what
            // `migrate_to_memstead_ref::extract_manifest_version` does).
            let version = manifest
                .lines()
                .find_map(|line| {
                    let t = line.trim_start();
                    t.strip_prefix("version:").map(|rest| {
                        rest.trim()
                            .trim_matches(|c: char| c == '"' || c == '\'')
                            .to_string()
                    })
                })
                .filter(|v| !v.is_empty())
                .unwrap_or_else(|| "0.0.0".to_string());
            // Walk the schema subtree (schema.yaml + types/*.yaml) and
            // mirror it under `schemas/<name>@<version>/`.
            let prefix = format!("schemas/{name}@{version}");
            let manifest_blob = repo
                .write_blob(manifest.as_bytes())
                .expect("write __MEMSTEAD schema manifest blob")
                .detach();
            memstead_editor
                .upsert(
                    format!("{prefix}/schema.yaml"),
                    gix::object::tree::EntryKind::Blob,
                    manifest_blob,
                )
                .expect("upsert __MEMSTEAD schema.yaml");
            let types_dir = path.join("types");
            if let Ok(types_rd) = fs::read_dir(&types_dir) {
                for type_entry in types_rd.flatten() {
                    let type_path = type_entry.path();
                    if type_path.extension().and_then(|s| s.to_str()) != Some("yaml") {
                        continue;
                    }
                    let type_name = match type_path.file_name().and_then(|s| s.to_str()) {
                        Some(n) => n.to_string(),
                        None => continue,
                    };
                    let body = match fs::read(&type_path) {
                        Ok(b) => b,
                        Err(_) => continue,
                    };
                    let type_blob = repo
                        .write_blob(&body)
                        .expect("write __MEMSTEAD type blob")
                        .detach();
                    memstead_editor
                        .upsert(
                            format!("{prefix}/types/{type_name}"),
                            gix::object::tree::EntryKind::Blob,
                            type_blob,
                        )
                        .expect("upsert __MEMSTEAD type yaml");
                }
            }
        }
    }
    // Vaults: per-vault config blobs rooted at
    // `vaults/<name>/config.json`.
    for (_rel, name, schema, belongs_to) in VAULTS {
        let body = main_configs_json(name, schema, belongs_to);
        let blob = repo
            .write_blob(body.as_bytes())
            .expect("write __MEMSTEAD vault config blob")
            .detach();
        memstead_editor
            .upsert(
                format!("vaults/{name}/config.json"),
                gix::object::tree::EntryKind::Blob,
                blob,
            )
            .expect("upsert __MEMSTEAD vault config");
    }
    let memstead_tree = memstead_editor.write().expect("write __MEMSTEAD tree").detach();
    let mut buf = gix::date::parse::TimeBuf::default();
    let actor_ref = actor.to_ref(&mut buf);
    repo.commit_as(
        actor_ref,
        actor_ref,
        "refs/heads/__MEMSTEAD",
        "vault-repo-seed: __MEMSTEAD",
        memstead_tree,
        Vec::<gix::ObjectId>::new(),
    )
    .expect("commit __MEMSTEAD");

    // Per-vault orphan branches with empty initial commits.
    let empty_tree = repo.empty_tree().id();
    for (_rel, name, _schema, _belongs_to) in VAULTS {
        let mut per_buf = gix::date::parse::TimeBuf::default();
        let actor_ref = actor.to_ref(&mut per_buf);
        let ref_name = format!("refs/heads/{}", name);
        repo.commit_as(
            actor_ref,
            actor_ref,
            ref_name.as_str(),
            "vault-repo-seed: empty initial",
            empty_tree,
            Vec::<gix::ObjectId>::new(),
        )
        .expect("commit empty initial on vault branch");
    }

    VaultRepoHandle {
        workspace_root,
        vault_repo_gitdir,
    }
}

/// `.memstead/workspace.toml` body — same vault roster as the live workspace, minus
/// `[branch_policy]` (removed engine-side; the
/// fixture omits it so the test surface does not depend on a
/// doomed knob).
///
/// `schemas_dir = "schemas"` is emitted as documentation-only: the
/// engine loads schemas from `vault-repo-git:__MEMSTEAD:schemas/` directly
/// (`memstead-git-branch::vault_repo_schemas::load_schemas_from_ref`), so the
/// disk-extracted shape the key seemed to imply was never wired.
/// Kept here to mirror the live workspace’s `.memstead/workspace.toml` so fixture-derived
/// tests exercise the same key surface, not to drive any loader
/// behaviour.
fn memstead_toml() -> String {
    let mut out = String::new();
    out.push_str("vaults = [\n");
    for (rel, _name, _schema, _belongs_to) in VAULTS {
        out.push_str(&format!("  \"{}\",\n", rel));
    }
    out.push_str("]\n\nschemas_dir = \"schemas\"\n");
    // Cross-vault edge authorization migrated from per-vault `belongsTo`
    // to workspace-level `[cross_vault_links]` (workspace-cross-link-
    // policy plan). Emit one entry per fixture vault that previously
    // declared a `belongsTo` list.
    let mut cross_links: Vec<(&str, &[&str])> = Vec::new();
    for (_rel, name, _schema, belongs_to) in VAULTS {
        if !belongs_to.is_empty() {
            cross_links.push((name, *belongs_to));
        }
    }
    if !cross_links.is_empty() {
        out.push_str("\n[cross_vault_links]\n");
        for (name, targets) in &cross_links {
            let arr: Vec<String> = targets.iter().map(|t| format!("\"{}\"", t)).collect();
            out.push_str(&format!("{} = [{}]\n", name, arr.join(", ")));
        }
    }
    out
}

/// Per-vault `.memstead/config.json` body. The `vcs` block points every
/// vault at the shared `vault-repo/.git/`; `worktree` points at the
/// workspace root. Under `StorageAdapterChoice::GitObject` the writer
/// uses `refs/heads/<name>` against this gitdir; under `Disk` (used
/// only by ad-hoc legacy tests, none in this fixture) the worktree
/// would be the vault dir, so this fixture's vcs shape is correct only
/// for GitObject mode.
fn vault_config_json(name: &str, schema: &str, _belongs_to: &[&str]) -> String {
    // Per-vault `belongsTo` is gone; cross-vault auth lives in the
    // workspace-level `[cross_vault_links]` section emitted by
    // `memstead_toml()`.
    format!(
        r#"{{
  "version": "0.1.0",
  "description": "vault-repo fixture: {name}",
  "schema": "{schema}",
  "vcs": {{
    "gitdir": "../../vault-repo/.git",
    "worktree": "../.."
  }},
  "writeGuidance": {{ "goal": "fixture vault for engine tests" }}
}}
"#
    )
}

/// Slimmer body for `__MEMSTEAD:vaults/<vault>/config.json` — same shape
/// the migration tool produces (no `vcs`, no `version`).
fn main_configs_json(name: &str, schema: &str, _belongs_to: &[&str]) -> String {
    format!(
        r#"{{
  "description": "vault-repo fixture: {name}",
  "schema": "{schema}",
  "writeGuidance": {{ "goal": "fixture vault for engine tests" }}
}}
"#
    )
}

/// Static seed signature — fixed times so tree/commit OIDs are stable
/// across runs, useful for tests that may want to compare across
/// fixtures.
fn fixture_signature() -> gix::actor::Signature {
    gix::actor::Signature {
        name: "vault-repo fixture".into(),
        email: "fixture@memstead".into(),
        time: gix::date::Time {
            seconds: 0,
            offset: 0,
        },
    }
}

/// `tests/fixtures/seed/schemas/` — committed schema YAMLs the builder
/// stages into the workspace. Resolved relative to the *consuming
/// crate*'s `CARGO_MANIFEST_DIR` because this file is `include!()`-ed.
fn seed_schemas_root() -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .join("..")
        .join("memstead-schema")
        .join("tests")
        .join("fixtures")
        .join("seed")
        .join("schemas")
}

/// Recursively copy `src` to `dst`, preserving directory structure
/// and file bytes. Mirrors the helper the previous fixture-driven test
/// used to stage the disk-shaped fixture into a tempdir.
fn copy_tree(src: &Path, dst: &Path) {
    if !dst.exists() {
        fs::create_dir_all(dst).expect("create dst dir");
    }
    for entry in fs::read_dir(src).expect("read seed dir") {
        let entry = entry.expect("read seed entry");
        let from = entry.path();
        let to = dst.join(entry.file_name());
        if from.is_dir() {
            copy_tree(&from, &to);
        } else {
            fs::copy(&from, &to).expect("copy seed file");
        }
    }
}

/// Walk a directory tree on disk and add every file as a blob entry
/// under `prefix` in the `gix` tree editor. Used to materialise the
/// schemas/ subtree on `vault-repo-git:main`. Sorting via `BTreeMap`
/// makes the produced tree deterministic.
fn walk_into_tree(
    repo: &gix::Repository,
    editor: &mut gix::object::tree::Editor<'_>,
    src: &Path,
    prefix: &str,
) {
    let mut entries: std::collections::BTreeMap<String, PathBuf> =
        std::collections::BTreeMap::new();
    for entry in fs::read_dir(src).expect("read schemas src") {
        let entry = entry.expect("schemas entry");
        let name = entry.file_name().to_string_lossy().into_owned();
        entries.insert(name, entry.path());
    }
    for (name, path) in entries {
        let rel = if prefix.is_empty() {
            name.clone()
        } else {
            format!("{}/{}", prefix, name)
        };
        let meta = fs::symlink_metadata(&path).expect("schemas entry meta");
        if meta.file_type().is_dir() {
            walk_into_tree(repo, editor, &path, &rel);
        } else if meta.file_type().is_file() {
            let bytes = fs::read(&path).expect("read schemas file");
            let blob = repo
                .write_blob(&bytes)
                .expect("write schemas blob")
                .detach();
            editor
                .upsert(rel.as_str(), gix::object::tree::EntryKind::Blob, blob)
                .expect("upsert schemas entry");
        }
    }
}
