//! Render the MCP tool catalogue as a Markdown reference. The server
//! (`McpServer`) exposes a static `tool_router()` associated function
//! generated by the rmcp `#[tool_router]` macro, so the live `Tool` list
//! can be lifted without booting an engine.

use rmcp::model::{Tool, ToolAnnotations};

use memstead_mcp::server::McpServer;

pub fn render() -> String {
    let tools = McpServer::tool_router().list_all();
    render_tools(&tools)
}

/// Sorted tool-name list. Sourced from the same router as [`render`];
/// consumed by the parity matrix.
pub fn tool_names() -> Vec<String> {
    let mut names: Vec<String> = McpServer::tool_router()
        .list_all()
        .iter()
        .map(|t| t.name.to_string())
        .collect();
    names.sort();
    names
}

fn render_tools(tools: &[Tool]) -> String {
    let mut sorted: Vec<&Tool> = tools.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = String::new();
    out.push_str("# MCP tools\n\n");
    out.push_str(
        "Generated from the live `tool_router().list_all()` catalogue on \
         `McpServer`. Every tool the running server exposes appears below.\n\n",
    );

    out.push_str(&format!(
        "**Count:** the server exposes {} tools.\n\n",
        tools.len()
    ));

    out.push_str("## Index\n\n");
    for tool in &sorted {
        let name = tool.name.as_ref();
        out.push_str(&format!("- [`{name}`](#{})\n", anchor(name)));
    }
    out.push('\n');

    for tool in &sorted {
        emit_section(&mut out, tool.name.as_ref(), tool);
    }
    out
}

fn anchor(name: &str) -> String {
    name.chars()
        .map(|c| match c {
            'A'..='Z' => c.to_ascii_lowercase(),
            'a'..='z' | '0'..='9' | '-' => c,
            '_' => '-',
            _ => '-',
        })
        .collect()
}

fn emit_section(out: &mut String, name: &str, tool: &Tool) {
    out.push_str(&format!("## `{name}`\n\n"));
    if let Some(desc) = &tool.description {
        out.push_str(desc);
        out.push_str("\n\n");
    }
    if let Some(annotations) = &tool.annotations {
        let line = render_annotations(annotations);
        if !line.is_empty() {
            out.push_str(&format!("**Hints:** {line}\n\n"));
        }
    }
    out.push_str("**Input schema:**\n\n```json\n");
    let schema_value = serde_json::Value::Object((*tool.input_schema).clone());
    let pretty = serde_json::to_string_pretty(&schema_value).unwrap_or_else(|_| "{}".to_string());
    out.push_str(&pretty);
    out.push_str("\n```\n\n");
}

fn render_annotations(a: &ToolAnnotations) -> String {
    let mut parts = Vec::new();
    if let Some(v) = a.read_only_hint {
        parts.push(format!("`read_only` = {v}"));
    }
    if let Some(v) = a.destructive_hint {
        parts.push(format!("`destructive` = {v}"));
    }
    if let Some(v) = a.idempotent_hint {
        parts.push(format!("`idempotent` = {v}"));
    }
    if let Some(v) = a.open_world_hint {
        parts.push(format!("`open_world` = {v}"));
    }
    parts.join(", ")
}
